// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatTheWorld.Infrastructure.Data;

#nullable disable

namespace WhatTheWorld.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203171823_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("WhatTheWorld.Domain.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagEmoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lon")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("Name");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "DE",
                            Capital = "Berlin",
                            FlagEmoji = "🇩🇪",
                            Lat = 52.520000000000003,
                            Lon = 13.404999999999999,
                            Name = "Germany"
                        },
                        new
                        {
                            Code = "US",
                            Capital = "Washington D.C.",
                            FlagEmoji = "🇺🇸",
                            Lat = 38.895099999999999,
                            Lon = -77.0364,
                            Name = "United States"
                        },
                        new
                        {
                            Code = "FR",
                            Capital = "Paris",
                            FlagEmoji = "🇫🇷",
                            Lat = 48.8566,
                            Lon = 2.3521999999999998,
                            Name = "France"
                        },
                        new
                        {
                            Code = "GB",
                            Capital = "London",
                            FlagEmoji = "🇬🇧",
                            Lat = 51.507399999999997,
                            Lon = -0.1278,
                            Name = "United Kingdom"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
